### ISSUE TITLE
Error: Line 1: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by dylang** [mgoldchild/nmv#1]
I tried in `node 0.11` and `node 4.1.2`.

```
❯ nmv
Error: Line 1: Unexpected token ILLEGAL
    at constructError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2388:21)
    at createError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2407:17)
    at unexpectedTokenError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2482:13)
    at throwUnexpectedToken (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2486:15)
    at scanPunctuator (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:840:13)
    at advance (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:1639:16)
    at peek (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:1712:78)
    at parseProgram (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:5423:9)
    at Object.parse (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:5611:23)
    at /Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/lib/read.js:15:35

/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:5623
            throw e;
            ^
Error: Line 1: Unexpected token ILLEGAL
    at constructError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2388:21)
    at createError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2407:17)
    at unexpectedTokenError (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2482:13)
    at throwUnexpectedToken (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:2486:15)
    at scanPunctuator (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:840:13)
    at advance (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:1639:16)
    at peek (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:1712:78)
    at parseProgram (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:5423:9)
    at Object.parse (/Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/node_modules/esprima/esprima.js:5611:23)
    at /Users/dgreene/.nvm/versions/node/v4.1.2/lib/node_modules/nmv/lib/read.js:15:35
```

**Comment by 3265** [comment]
Fixed esprima hashbang parse error by f815b1e9995b37c7db334f1dc757bdd2cae98b18.
